### ISSUE TITLE
Crash on launch in some system locales

### ISSUE THREAD

**Issue by MandL27** [Rangi42/tilemap-studio#25]
When launching Tilemap Studio, either latest release or built from source, on a Windows 10 machine with non-Unicode system locale set to Japanese, the process appears for a couple seconds before abruptly terminating. Launching through Visual Studio produces the following error:
![image](https://user-images.githubusercontent.com/10366615/118170721-6e605380-b3f8-11eb-8826-525d80bb267e.png)
I switched locale back to en-US and everything worked again.

**Comment by Rangi42** [comment]
I've previously used tools like [AppLocale](https://en.wikipedia.org/wiki/AppLocale) or [Locale Emulator](https://xupefei.github.io/Locale-Emulator/) to run Japanese programs on a system with US English as the non-Unicode system locale. Does that help you with Tilemap Studio? Or, are you using a limited set of Japanese programs, and can they be run with a non-default locale instead?

I don't plan on testing or supporting locales for Tilemap Studio. The FLTK library uses UTF-8 internally, which is increasingly standard, and already has to work around some issues with Windows having standardized on UTF-16. ([Turns out](https://github.com/Rangi42/polished-map/issues/43) that C++'s `std::ifstream` doesn't work with special characters and there's no wide-char equivalent, but FLTK's `fl_fopen` works correctly... at least for Unicode applications.)

If this is something that you can debug and fix, that doesn't require some kind of locale awareness code added in all sorts of places, I'd appreciate a PR.
