### ISSUE TITLE
Layer Supporting

### ISSUE THREAD

**Issue by Dragonflysots** [Rangi42/tilemap-studio#37]
It is specifically about layer based background creation and also dynamic maps. So the rendering alone would be enough, then you could export each background separately as a bin file.

For example, to redesign a title screen to have a preview in the program. What would also be good, if you could turn the individual backgrounds (for visual representation) also the transparency up and down.

**Comment by Rangi42** [comment]
None of the supported tilemap file formats have layers; so this would involve an intermediate file format, like Photoshop's .psd or paint.net's .pdn. And I don't think it would ultimately be useful, since if some tiles overlap, the top layer would just overwrite the others. For the stage of graphic design where you'd want layers, I'd recommend an actual graphics editor like paint.net or GIMP (or something specific to pixel art like Aseprite). Then when you've exported a single .png design, use Image to Tiles on that.
