### ISSUE TITLE
Allow generating "suboptimal" tilesets with Image to Tiles

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/tilemap-studio#63]
Underneath the "Avoid extra blank tiles at the end" checkbox could be two more: "Don't flip tiles" and "Don't deduplicate tiles" next to each other, both unchecked by default.

"Don't flip tiles" would be enabled iff the selected format allows flipping.

"Don't deduplicate tiles" would be enabled iff "Don't flip tiles" is checked.

Checking these would allow redundant tiles in the tileset, which is usually not what people want, but sometimes is.

**Comment by Ryuhouji** [comment]
For my use case, having the image directly inserted in the rom without changing the data makes it easy to make touch ups later if you decide you want to do so. It also makes it much easier to quickly recognize which image you are looking at. This allows you to just directly edit the image with the image editor of choice and save it without any further effort required. No need to completely remake the tilemap.

My use case is niche, though, because I prioritize ease of use & access over optimization and saving space.

**Comment by Rangi42** [comment]
Mockup:

![image](https://user-images.githubusercontent.com/35663410/160260912-68cc4471-a69e-4665-a9fc-f06e09b72a55.png)
